### ISSUE TITLE
Please remove your header line for 'Update URI'

### ISSUE THREAD

**Issue by shishirraven** [shishirraven/custom-user-fields#2]
## Please remove your header line for 'Update URI'

In WordPress 5.8, a new plugin header was introduced called "Update URI." This header was created to permit plugins hosted outside of WordPress.org to block updates of their plugins in a safe manner.

Authors of plugins hosted by WordPress.org don’t need to use this new header, and in fact do not want to at all. It's only beneficial to non-WordPress.org plugins

https://make.wordpress.org/core/2021/06/29/introducing-update-uri-plugin-header-in-wordpress-5-8/

In order to prevent missteps, we are asking developers to remove that from their code.

Example(s) from your plugin:

custom_user_fields.php:22: * Update URI: https://iamshishir.com/visual-user-fields-wordpress-plugin/

**Comment by kishankumar999** [comment]
removed your header line for 'Update URI' 
[b6a16c7](https://github.com/shishirraven/custom-user-fields/commit/b6a16c7bdd6a32ca83fad526b8ce1d59e80b7987)
