### ISSUE TITLE
Add Help text similar to how it is shown in the following Image. 

### ISSUE THREAD

**Issue by shishirraven** [shishirraven/custom-user-fields#7]
![image](https://user-images.githubusercontent.com/4470383/200527315-55badd0d-299e-419b-bcaa-297249853f0f.png)

**Comment by kishankumar999** [comment]
Help text id added.
[354f20d](https://github.com/shishirraven/custom-user-fields/commit/354f20ddfb2c60acabaf33b33c674a3d27e35cfd)
